name: Code style and test
concurrency:
  group: on_push
  cancel-in-progress: true

on:
  push: {}
  workflow_dispatch: {}

jobs:
  code-style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python for Poetry
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install poetry
        run: |
          python -m pip install poetry pip
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: |
          poetry install -n
          poetry run pip install -U aiobotocore types-aiobotocore
          poetry install -n
      - name: Install Node.js dependencies
        run: |
          npm install -g pyright
      - name: Lint
        run: |
          poetry run flake8 istub
          poetry run npx pyright istub
          poetry run mypy istub
          poetry run black --check istub
          poetry run isort -c istub
