name: Code style and test
concurrency:
  group: on_push
  cancel-in-progress: true

on:
  push: {}
  workflow_dispatch: {}

jobs:
  code-style:
    name: Code style
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
        include:
          - version: "3.12"
            check-formatting: "true"
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: |
          pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
          cache: "poetry"
      - name: Install dependencies
        run: |
          poetry install -n
      - name: Code style
        if: ${{ matrix.check-formatting }}
        run: |
          poetry run ruff format --check
      - name: Lint
        if: ${{ matrix.check-formatting }}
        run: |
          poetry run ruff check
      - name: Typing
        run: |
          poetry run pyright
      - name: Check istub run
        if: ${{ matrix.check-formatting }}
        run: |
          poetry run istub -buid
